version: '3'

networks:
    laravel:

services:
    nginx:
        container_name: project_idea-nginx
        image: nginx:stable-alpine
        ports:
          - "7077:80"
        volumes:
          - ./:/var/www/html
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php
          - mysql
        networks:
          - laravel

    mysql:
        image: mysql:8
        container_name: project_idea-mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
          - ./mysql:/var/lib/mysql
        environment:
          MYSQL_DATABASE: project_ideas
          MYSQL_USER: root_user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          SERVICE_TAGS: dev
          SERVICE_NAME: mysql
        networks:
          - laravel

    php:
        build: ./
        container_name: project_idea-php
        volumes:
            - ./:/var/www/html
        networks:
          - laravel